### ISSUE TITLE
Implement a save/load system to make setting persistent

### ISSUE THREAD

**Issue by quellus** [quellus/GDTuber#1]
There should be a save/load system so settings don't get reset every time the program is restarted

Persistent settings include:
* Microphone threshold level
* Avatar image and settings
* Selected microphone
* Avatar position and size

* Avatar drip (when implemented)

**Comment by M-125** [comment]
I may want to take this
If i dun forget XD

**Comment by quellus** [comment]
This issue is rapidly growing as we add features.
Current status:

- Microphone threshold
- Selected microphone
- Save multiple sprites including
  - position
  - scale (if #5 is complete)
  - path to the image file
  - talking boolean (whether or not the avatar has a mouth)
  - blinking boolean (whether or not the avatar has a blinking animation)
  - reactive boolean (whether or not the avatar should bounce when talking)

**Comment by M-125** [comment]
huh
big stuff

**Comment by M-125** [comment]
gonna pr idk how should i make mic select saved yet
