### ISSUE TITLE
Change project icon

### ISSUE THREAD

**Issue by quellus** [quellus/GDTuber#10]
I'm open to suggestions on what the icon should be. For now, since we have a default avatar, let's set it to the mouth open and eyes open image of the default avatar

**Comment by spaghetticodefactory** [comment]
**Colored**

![grafik](https://github.com/quellus/GDTuber/assets/173544387/2da17ca6-65da-48ef-b601-e6bd2285fe15)

**Mono**
![grafik](https://github.com/quellus/GDTuber/assets/173544387/673d27cb-47d5-4e7a-a8eb-c76f1206e79f)

**Comment by quellus** [comment]
It gives very 2005 windows app, but maybe that's a vibe?

**Comment by Giganzo** [comment]
![image](https://github.com/quellus/GDTuber/assets/158825920/8fcc375f-5885-4c03-b4c2-66710e24048b)

**Comment by quellus** [comment]
Latest WIP from @spaghetticodefactory 

![image](https://github.com/quellus/GDTuber/assets/60303040/8b08b1b8-d21f-4918-aff0-f0f145f10a04)

**Comment by tech-with-the-unkownguy** [comment]
![Default_Design_a_vibrant_logo_for_a_GDTuber_featuring_an_styli_0](https://github.com/quellus/GDTuber/assets/158983274/dc6a6adb-fe02-4d60-b6fd-003ade39d791)

**Comment by tech-with-the-unkownguy** [comment]
![Default_Design_a_vibrant_logo_for_a_PNGtuber_featuring_an_styl_0](https://github.com/quellus/GDTuber/assets/158983274/4d26f4bb-4705-430f-879f-3c2ec67f95d8)

**Comment by Giganzo** [comment]
![image](https://github.com/quellus/GDTuber/assets/158825920/70b62180-137c-4104-977e-1a1a99c3a8a0)

**Comment by spaghetticodefactory** [comment]
![grafik](https://github.com/user-attachments/assets/16e12bb0-98d4-49af-8612-99f4fbfe23f3)

The dotted line is meant to show how it would look as a square icon in the taskbar
