### ISSUE TITLE
Cleanup debug warnings

### ISSUE THREAD

**Issue by quellus** [quellus/GDTuber#16]
**Is your feature request related to a problem? Please describe.**
When opening the program in the Godot engine, there are a lot of debug warnings. These warnings should be resolved. Most of these are incredibly simple to solve and a some of them could solve potential future bugs.

Warnings, while seeming harmless, could cause bigger issues when we create a release. It's good practice not to ignore them.

**Describe the solution you'd like**
Resolve all debug warnings. The debugger should give no warnings or errors when running the project.

**Describe alternatives you've considered**
There are two alternatives:
1. Debug warnings can be ignored in the project settings
2. We can just actually ignore the yellow text that pops up in the editor

**Comment by code807** [comment]
Debug warnings were cleared as of #39
