### ISSUE TITLE
Add setting to change bounce height and speed

### ISSUE THREAD

**Issue by quellus** [quellus/GDTuber#24]
**Is your feature request related to a problem? Please describe.**
There isn't currently a way to change the height and speed of the bounce animations. I would like to be able to change this on the fly.

**Describe the solution you'd like**
The settings menu should have sliders, buttons, or text inputs for bounce speed and height. I think sliders will be the best way to go for this.

**Describe alternatives you've considered**
The only alternative is to expect the user to edit the source code and change the hard coded values. This is bad user experience.

**Additional context**
The bounce animation is an `Animation` we're generating through code when the sprite is created. We may be able to edit the animation directly. I'm worried we might have to regenerate the animation every time it's changed.

We may want to consider replacing the `AnimationPlayer` with a tween. It sounds like it could be a lot easier to use.

**Comment by spaghetticodefactory** [comment]
Using tweens would be the smart solution, I agree.
