### ISSUE TITLE
Add the ability to change avatar size and position in the program

### ISSUE THREAD

**Issue by quellus** [quellus/GDTuber#5]
The user shouldn't have to edit the source code and recompile the program just to change the avatar's size and position. The user should be able to change it at runtime via the config menu in the program.

**Comment by quellus** [comment]
Avatar position is complete. Now we just need to add scaling

**Comment by quellus** [comment]
I was hoping it would be as easy as slapping a slider on the settings menu, but the way sprites can have dramatically different sizes based on texture resolution adds a lot of complexity to the situation.

I'm going to have to rethink how I go about this. An ideal situation is to have sprites scale themselves based on texture resolution so every sprite has the same initial "size".

**Comment by jo372** [comment]
Just putting this comment so people don't start working on it! :) I have scroll wheel scaling working here: https://github.com/quellus/GDTuber/pull/29
