### ISSUE TITLE
Setting to toggle full screen

### ISSUE THREAD

**Issue by quellus** [quellus/GDTuber#6]
Having a transparent window start fullscreen is pretty scary if you don't expect it. The program should start windowed with a border to alleviate confusion and have a setting in the settings menu to toggle fullscreen.

**Comment by spaghetticodefactory** [comment]
Fixed with #31

**Comment by spaghetticodefactory** [comment]
thanks for unwinding my messy PR

Should I reintegrate my fullscreen toggle the same way I had it in the PR or do you have any feedback?

**Comment by quellus** [comment]
@spaghetticodefactory I think the only feedback we had was not to change the signals. They should be connected in the editor.

I’m not sure if I accidentally closed your PR or not. Sorry if I did
