### ISSUE TITLE
[Feature Request]: Save files should be `.gdt` extension

### ISSUE THREAD

**Issue by quellus** [quellus/GDTuber#90]
### Is your feature request related to a problem? Please describe.

Users may find unrelated JSON files and think they are valid configs for GDTuber. Giving save files a custom extension can both make it easier to remember what the file is, and prevent users from trying to load the wrong file.

### Describe the solution you'd like

Save files should be saved with the `.gdt` extension.
When loading a file, the file dialog should filter to `.gdt` files

**Comment by Yagich** [comment]
`.gdt` could potentially be used in the future by Godot for trait files, so maybe make it more explicit like `.gdtuber`?

[(reference)](https://github.com/godotengine/godot-proposals/issues/6416)
